### PR TITLE
nwHacks grading buckets eval filter

### PR DESCRIPTION
**Pull request by tdanielles**
## Description
- ticket: https://www.notion.so/nwplus/nwHacks-app-grading-buckets-12914d529faa8028884dd14267af9823?pvs=4
- added the 4 filters requested above
- for the num experiences, i made it 0-5, lmk if you want smth different
- added a num experiences area in scoring section with a weight of 0 
- changed "see count" button such that if everything is empty it will just return count of applicants unfiltered
- changed ui to make it look better but lmk if any changes needs to be made

### CODE REVIEW

**Comment by alvinkam33** [comment]
this is looking really good! verified that the new # experiences field and all filters should be working properly too

@tdanielles for clarity and visibility, could we add year level and num hackathons attended somewhere in the Applicant Response section?

other than that ill run this by logs and i think we'll be good

**Review by DonaldKLee — CHANGES_REQUESTED** [review]
LGTM!

Minor bug, recommend adding overflow hidden
- there's a horizontal and vertical scroll bar on the pop up modal
image

**Comment by tdanielles** [comment]
> this is looking really good! verified that the new # experiences field and all filters should be working properly too
> 
> @tdanielles for clarity and visibility, could we add year level and num hackathons attended somewhere in the Applicant Response section?
> 
> other than that ill run this by logs and i think we'll be good



> LGTM!
> 
> Minor bug, recommend adding overflow hidden
> 
> * there's a horizontal and vertical scroll bar on the pop up modal
>   image

@alvinkam33 added! 

@DonaldKLee - fixed the horizontal scrollbar issue - lmk if it's good now! i left the vertical scrollbar for now because the side bar extends all the way past the size of the evaluator and the vertical scrollbar is also present when the accepting modal isn't toggled
Screen Shot 2024-11-30 at 6 07 49 PM

**Review by alvinkam33 — APPROVED** [review]

**Review by DonaldKLee — APPROVED** [review]
lgtm!

**Pull request merged**
