### PR TITLE
Read/write firestore

### LINKED ISSUE #127: Section > Scoring
Scoring across all sections, total score should update upon save and once all section's are marked there should be a toggle to "Completed" on the applicant's profile and ability to add tags to an applicant

Screen Shot 2021-11-06 at 9 43 27 PM

### PR DESCRIPTION
**Pull request by kevin-zou**
## Description
Closes #127. Pull applicants from Firebase and allow admin to be able to write scores + comments. Also added the `Last updated by` information (although I'm not sure if the font is accessible 😅 )

Also I've decided to only write to Firebase when the user clicks "Save". Previously we were writing whenever a score for any category was selected. I think this new UX makes sense and decreases the number of writes.

Yes the buttons on the left are super scuffed, but it'll be better when the component is finished for that!
image
 
## Other considerations
Small changes in other files:
- added `''` as comment placeholders in `Assessment/applicantScore.js` just to support the old evaluation portal

### CODE REVIEW

**Comment by kevin-zou** [comment]
Can somebody try this out on the preview branch and make sure that when you edit someone's scores it has your email instead of mine? 🙏

**Comment by phoenixthefirebird** [comment]
Comment 1:
I tried selecting the score when no applicants are selected and I get this error
image
Should we hide the scoring section when no applicant is selected? Or is that an UI thing to be worried about later?
Comment 2: 
image
Last updated indeed shows the correct email of the current admin so yay!
Comment 3: 
I can wait till this is merged and update where you commented with the HackerEntry component in my open issue.

**Comment by kevin-zou** [comment]
@phoenixthefirebird re: your first comment, hiding it makes sense (that's the behaviour in old assessment) If it's okay with you I was thinking of leaving this task to the PR that puts together all the components, since it will be handling the state of who the currently selected hacker

**Review by phoenixthefirebird — APPROVED** [review]
GO

**Pull request merged**
